steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/${_GIT_ACCOUNT}/${_REPO_NAME}.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: pycaret-kubernetes-demo2
    _REGION: us-central1
    _GKE_CLUSTER: insurance-cluster
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: insurance-app
    _CONTAINERNAME: insurance-appp    
    _GIT_ACCOUNT: aadityak27111987
    _REPO_NAME: pycaret-deployment-google2
    
    # Developers ONLY change
    _VERSION: v1.3
    
options:
    substitution_option: 'ALLOW_LOOSE'

